### ISSUE TITLE
app_id needed on Staging for Facebook

### ISSUE THREAD

**Issue by cesy** [Growstuff/growstuff#1053]
When trying to sign in with facebook (registering a new account) on Staging, I get this error:

The parameter app_id is required

Do we need to configure something to sort this? Will we need to do the same on prod?

**Comment by CloCkWeRX** [comment]
For staging; App ID 1471371409831859 should do the trick.

I deliberately only registered Growstuff Dev; so that with the prod configuration someone other than just me could own it.
![image](https://cloud.githubusercontent.com/assets/365751/19630002/eb7a06bc-99c8-11e6-83d3-7c36ded838e9.png)

#811 added:
http://localhost:3000/
```
GROWSTUFF_FACEBOOK_KEY: ""
GROWSTUFF_FACEBOOK_SECRET: ""
```

I'll add everyone as an admin in a bit, but it wants facebook accounts rather than emails which is annoying.

**Comment by maco** [comment]
So what needs to be done to  make this stop blocking release 15?

**Comment by CloCkWeRX** [comment]
Chuck your fbid into an email to me or similar; though it gave me trouble with adding pozorvlak.

**Comment by pozorvlak** [comment]
I've now set GROWSTUFF_FACEBOOK_KEY and GROWSTUFF_FACEBOOK_SECRET on http://staging.growstuff.org. It turned out that I couldn't use the same app for localhost and for staging.growstuff.org, so I created a new growstuff-staging app (ID 146446135831722) and added @maco and @CloCkWeRX as administrators. @cesy, do you have a Facebook account?

Anyway, after all that, I could log in with Facebook! And it was able to connect my Facebook account to my already-existing growstuff-staging account o_O

**Comment by pozorvlak** [comment]
So I guess if someone else can confirm that "sign in with Facebook" works on staging, we can create an FB app for production, and finally push release 15 live?

**Comment by maco** [comment]
Yep, logging into Staging with Facebook worked for me.

**Comment by CloCkWeRX** [comment]
Closing off as fixed based on the 'works for me' above
