### ISSUE TITLE
Seeds.collected_at

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#1553]
Ā modifiable date, indicating when the seeds where collected from a planting.

**Comment by pozorvlak** [comment]
I have some n00b questions:

 - What do you want this for?
 - Do you only want it for collected seeds? Would it make sense to generalise it to "obtained_at", which could cover the date packets of seeds were bought?
 - Do we want "best before" dates as well/instead?
 - Is "best-before date" a globally-understood term? If not, what would be a better one?
 - Why should it be modifiable? How many times? Do we need to track history of dates? (er, meta-history? historiography?)

**Comment by Br3nda** [comment]
When seeds are saved from their parent planting, it's useful to see the date they were collected. That's what i want it for -- when viewing the planting (especially perennials) I want to see what seeds it produced and when, not just 4 lots of seeds over 2 years.

I have no idea what a "best before" would be for tomato seeds I saved yesterday.  Maybe they're just for the seed you've bought from a commercial seed supplier? Best-before sounds like something you'd see on a milk bottle. I think "sow before" might be better for me.

It should be modifiable so you can record today the seeds that you collected 4 weeks ago.

This maybe makes more sense once you see the PR #1550
![image](https://user-images.githubusercontent.com/12266/35244137-08fee168-0024-11e8-8170-237a43cf2d37.png)

**Comment by Br3nda** [comment]
The date i saved is what i write on packets becuse i use that to decide what and when to plant. Having this all in a database is more useful than digging through packets in the shed.

**Comment by pozorvlak** [comment]
OK, I think I see. Is the following correct?

 - You want to know when a given packet of seeds needs to be planted by, but that's hard to calculate, so you store the date they were collected and decide "that should be planted soon" nearer the time.
 - Also, dates of seed-collections give you useful information about the parent plant.
 - You manage commercially-bought seeds through a different process (what is it? Could it benefit from tool support?)
 - "Best-before date" is not a globally-understood term, at least not in this context.
 - The date needs to be user-settable at least once, at creation time. It probably also needs to be modifiable afterwards because people make data-entry errors. But once set correctly it should not need to change again.

**Comment by pozorvlak** [comment]
Oh, I see we already have a field for "plant before".

**Comment by Br3nda** [comment]
I'm not interested in the plant before dates. But that's existing functionality that we can keep.
I'm interested in where the plants came from. If the sunflowers are getting more yellow. If the garlic is getting bigger. If the kamokamo i have is getting more like a kamokamo and less like a pumpkin. If the tomatoes are keeping their heirloom quality. I want to see the date the seed was collected from the plant. I might record seeds i collected last year, so it needs to be editable.

**Comment by Br3nda** [comment]
How about the collected_at only appears on seeds that are known to be collected from a planting?

**Comment by pozorvlak** [comment]
Right! OK, that all makes sense.

**Comment by Br3nda** [comment]
done as `seeds.saved_at`
