### ISSUE TITLE
Rewrite default_photo code to not make lots of db queries. 

### ISSUE THREAD

**Issue by Br3nda** [Growstuff/growstuff#2326]
Part of #1640

**Comment by Br3nda** [comment]
added some caching to help in the meantime #2327

**Comment by simicic** [comment]
@Br3nda I would love to pick up this issue but I would like to know what is expected. 
From what I see, the original issue is with slowness of `HarvestController#index` and the n+1 query for the default photo as defined in `PhotoCapable#default_photo`?
Is the idea to load the association from the controller in order to show it in the view or something else?
(Btw, I did not spend a lot of time in the project - maybe a different issue is better to start with - in any case, I like the project and I would like to help out!)

**Comment by Br3nda** [comment]
This is already mostly done in #2320.
