### ISSUE TITLE
Fix community map

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#3189]
Reproduce steps:

- https://www.growstuff.org/places

Migration guide:
https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4

**Comment by le-jun** [comment]
From my understanding, we’re running Mapbox Leaflet v4 whereas the latest version is 12. The issue seems quite easy to fix by tweaking some lines [here](https://github.com/Growstuff/growstuff/blob/5ebe0de7d9179cdb557dd68dfb8934e1f6c6e1e4/app/assets/javascripts/places.js.erb) according to [official documentation](https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/). The use of multiple variables in addition to Ruby makes me unable to do the fix myself and learning Ruby is quite low on my to-do list.
