### ISSUE TITLE
Shutter the twitter account?

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#3403]
https://twitter.com/growstufforg + footer links.

Dunno if any of us actually control it.

The various kneejerk changes so our feeds aren't public anymore, and the mass migration of communities to elsewhere (https://www.zdnet.com/article/twitter-seeing-record-user-engagement-the-data-tells-a-different-story/) is probably justification enough, but the wider it's a billionare-having-a-tantrum dynamics of it vs us being a community oriented open source effort makes it seem like a poor fit.

Alternatives could be:
* Do nothing.
* Mastodon - https://mastodon.world/tags/vegetablegarden - there seems to be at least discussion on topics vaguely related to us

**Comment by cesy** [comment]
I think I still have login details saved in the shared passwords tool, I can have a look. I'm definitely in favour of shutting it in some way, probably by blanking out the account but keeping the username so no-one can impersonate us, and pointing people directly at our website? The discussion on Mastodon is probably more useful in our personal accounts rather than as an official one, but I'd be happy for you or one of our other volunteers to run an official one if you'd like.

**Comment by cesy** [comment]
I got in and have posted a message, let me know if you want anything further added to it to point people elsewhere.
