### ISSUE TITLE
On homepage, post activity times are out of date

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#488]
On the homepage, where there's a list of recently active posts, the activity times ("1 day ago" etc) get out of whack.  For instance, the most recent post _always_ says "less than a minute ago" even when it's quite old.

This appears to be a caching problem.  We should probably expire the recent_posts cache regularly (maybe once an hour?) even if there are no new posts/comments.

**Comment by Skud** [comment]
This issue will no longer be relevant once #628 is done.

**Comment by CloCkWeRX** [comment]
This came up even though there was some work done to address it during recent testing on staging.

Posts at the bottom of the homepage were all saying they were "1 minute ago", because they got cached straight after posting. They now say the right date.

* View homepage
* Login
* Post something
* View homepage again
Expected: A date+time is shown or other relevant indicator

Actual: Only dd-MM is rendered. I can't tell if there are new posts today; or if staging was last updated April 2, 2015. Should adjust format to (3pm 1 Jan 2016) or add in a title attribute with the full details, so I can mouseover and understand it.

**Comment by Br3nda** [comment]
seems fixed now.
