### ISSUE TITLE
Produce/harvest trading

### ISSUE THREAD

**Issue by Skud** [Growstuff/growstuff#563]
This is a placeholder for the idea of enabling trading of harvested produce.  For instance, if I have harvested 10kg of zucchini and don't want them, I could offer them up on Growstuff, Growstuff would notify people near me, blah blah.  Not sure yet how this would work but it's on the far-future roadmap.

**Comment by CloCkWeRX** [comment]
Unfortunately, there's a lot of things to consider with creating a farmer's market or food cooperative.

IE:
https://farmersmarkets.org.au/starting-a-market/

And

Food Acts
Any person that sells foods must comply with their state or territory Food Act. The Food Acts 
include penalties for persons who sell unsafe or unsuitable food. It is also an offence to handle 
food intended for sale in a manner that will make, or is likely to make, the food unsafe. The 
definitions for unsafe and unsuitable food are contained with these Food Acts. The state and
territory Food Acts can be accessed at:
http://www.foodstandards.gov.au/about/background/foodlaw/Pages/default.aspx. 
In summary:
unsafe food is food that is likely to cause physical harm to a person, provided that the food is 
used as it is intended to be used. For example, raw sausages are considered to be safe, even 
if contaminated with pathogenic microorganisms, as they are intended to be cooked before 
consumption. 
unsuitable food is food that:
• is damaged, deteriorated or perished 
• contains a matter or substance that is foreign to the nature of the food
• is the product of a diseased animal or an animal that has died otherwise than by slaughter.
Other penalties apply for misleading and deceptive conduct in relation to the sale of food and 
selling food that is falsely described. 
Food Standards Code
The state and territory Food Acts also include penalties for persons who sell food that does not 
comply with any requirements of the Code that relates to the food. And if you are a food 
business, penalties apply if you do not comply with the requirements on food businesses as 
set out in the Code. The Code, and all the standards it contains, can be accessed from:
http://www.foodstandards.gov.au/code/Pages/default.aspx

Another area is potentially donating to good banks, but again that has a high barrier:
https://www.foodbank.org.au/hunger-in-australia/what-we-do/working-with-farmers-growers/fruit-veg/?state=sa


In our current form, and considering we are spread across the world, the best we can probably do here is a "I'm willing to share" checkbox on the harvest with a contract grower button, slathered in disclaimers and warnings to comply with local regulations, or a one click "post to gumtree", or even a "find cheap ((cropname))" with a link to wholesalers.
Even then, though I have sometimes got excess produce, I'm often better served by canning and preserving.

For now, closing (can be replaced by more specific ideas)
