### ISSUE TITLE
Feature test fails since pull request # 728 was merged.

### ISSUE THREAD

**Issue by GabrielSandoval** [Growstuff/growstuff#773]
@pozorvlak could you check on this one?

**Comment by CjayBillones** [comment]
Same thing happened to me ever since I rebased my dev branch (without any other commits, just a pure copy of the upstream/dev)

![screenshot from 2015-07-09 13 38 11](https://cloud.githubusercontent.com/assets/8434127/8588676/d9d2da72-263f-11e5-8fa5-662455eaa6f5.png)

![screenshot from 2015-07-09 13 38 27](https://cloud.githubusercontent.com/assets/8434127/8588686/edc74978-263f-11e5-8055-dd1f4071ed0c.png)

![screenshot from 2015-07-09 13 38 36](https://cloud.githubusercontent.com/assets/8434127/8588691/fd31f052-263f-11e5-8aca-053badf4bb15.png)

**Comment by maco** [comment]
Can you show the text further up, above the listed failures?

I did have a weirdness recently where identical code on my desktop and laptop, the tests failed on laptop, and handily I was at a Ruby developer conference at the time, and someone helped debug, and we found it was PhantomJS causing a end-of-file in capybara, and PhantomJS isn't something controlled by Bundler, so I had different versions on the two computers. 

(This just seems relevant since the tests are passing in Travis)

**Comment by CjayBillones** [comment]
@maco here's a file containing all the errors.

http://www.mediafire.com/view/o1r6ycds2cn99mo/fail_tests.txt

**Comment by pozorvlak** [comment]
Weird. It's working fine for me: what's the output of `git show HEAD`?

**Comment by CjayBillones** [comment]
@pozorvlak 
![screenshot from 2015-07-10 07 32 46](https://cloud.githubusercontent.com/assets/8434127/8609287/edf6d7b0-26d5-11e5-8d95-66fe3f45c759.png)

**Comment by pozorvlak** [comment]
I just checked out that commit and ran `rspec`, and everything passed. Try running `rake db:test:prepare` and then run the tests again? DB syncing problems are a common cause of "lots of inexplicable test failures".

**Comment by pozorvlak** [comment]
Wait, forget the last thing I said. Looking at `notifier.rb` line 11, it looks like this may be related to RAILS_SECRET_TOKEN. We should probably change that code to use `Growstuff::Application.config.secret_key_base` rather than `ENV['RAILS_SECRET_TOKEN']` - they're the same on staging and production, but not on test and development. But I don't have that environment variable set to anything and tests are passing for me, so that can't be the whole story.

**Comment by pozorvlak** [comment]
Aha! I'm setting RAILS_SECRET_TOKEN in application.yml. Try doing that, and running tests again?

I'm now rather confused about what variables we should set and read where: @Cesy, do you have any insight here?

**Comment by CjayBillones** [comment]
Okay, I figured out what was wrong in my case. I forgot to set-up may application.yml when I set-up the project in another machine.

**Comment by cesy** [comment]
I vaguely remember there was a Heroku reason for doing it this way round, but yes, application.yml is crucial.

**Comment by GabrielSandoval** [comment]
I think we should close this issue already.

**Comment by pozorvlak** [comment]
Cool - if everything's working for you both, I'm happy to close it :-)
