### ISSUE TITLE
Needs more work: Thumbnails of crops should now show on a post where you reference a crop

### ISSUE THREAD

**Issue by CloCkWeRX** [Growstuff/growstuff#877]
This certainly works:
http://staging.growstuff.org/posts/clockwerx-20160422-where-s-my-lettuce

but its not my photo of _my_ lettuce; nor is it really easy to discover the feature. It's very likely I would be talking about my lettuces, not generic lettuce in general

**Comment by maco** [comment]
Thinking about this, I have questions:

1. If you make a post about a problem you're having with your lettuce, years later, should it still show the most-recent-lettuce-photo-as-of-post-date or should it show the most recent lettuce photo as of reading time? The latter could be confusing if you're saying "why's it got spots?"

1. Fall back to the most popular lettuce photo if you don't have one of your own?

(This latter slides into the "we should have uprooting on photos" story)

**Comment by CloCkWeRX** [comment]
One thought: http://yuku-t.com/jquery-textcomplete/ might be a good UI approach to let a user choose what they want depicted.

Github's comment forms allowing you to paste in an image and it gets replaced with an exact URI seem quite usable - doing the same for [lettuce/photo/38](lettuce) vs [lettuce/photo/current](lettuce) might be quite workable, with a sufficiently friendly control to show you how.

**Comment by maco** [comment]
I was thinking earlier today of something related.

You might want to put a photo in a post without necessarily attaching it to a planting/garden/harvest. Being able to select from your Flickr and have it do the right thing with markdown (because Flickr only has HTML or bbcode options) would be neat. And then someday when we do photo uploading, posts would be a place to do that too.

**Comment by Br3nda** [comment]
I've added photos directly to a post on #2041
